/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetClavardage.Model;

import java.sql.Connection;

public class App {

    public static void main(String[] args) {
        DatabaseManager.createTables();
        DatabaseManager.addUser("user1", "MonsieurSinge");
    }
}
