/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetClavardage;

import ProjetClavardage.View.AppFrame;

import java.sql.Connection;

public class App {

    public static void main(String[] args) {
        new AppFrame();
    }
}
