/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetClavardage;

import ProjetClavardage.View.AppFrame;

public class App {

    public static void main(String[] args) {
        AppFrame appFrame;
        appFrame = new AppFrame(args[0], Integer.parseInt(args[1]), Integer.parseInt(args[2]), Boolean.parseBoolean(args[3]));
    }
}
