/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetClavardage;

import ProjetClavardage.Controller.MainController;
import ProjetClavardage.Model.MessageThreadManager;
import ProjetClavardage.View.AppFrame;

public class App {

    public static void main(String[] args) {
        AppFrame appFrame;
        // program arguments : username, TCP client port, TCP server port, UDP client port, UDP server port, isFullscreen, networkInterface
        appFrame = new AppFrame(args[0], Integer.parseInt(args[1]), Integer.parseInt(args[2]), Integer.parseInt(args[3]), Integer.parseInt(args[4]), Boolean.parseBoolean(args[5]));
    }
}
